.\"
.\" Copyright (c) 2019 Ted Unangst
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt HONK 1
.Os
.Sh NAME
.Nm honk
.Nd federated status conveyance
.Sh SYNOPSIS
.Nm honk
.Sh DESCRIPTION
The
.Nm
utility processes status updates and other microblog activities.
This is the user manual.
For administration, see
.Xr honk 8 .
.Pp
This manual is very incomplete.
Refer to the text files.
.Ss Following
In order to receive posts from other users, one must follow them.
Begin at the
.Pa honkers
tab.
The
.Ar url
field is required.
Either of two forms are accepted, the user's handle (or webfinger) or their
ActivityPub actor URL.
The
.Ar name
field is optional and will be automatically inferred.
Examples:
.Dl @user@example.social
.Dl https://example.social/users/user
.Pp
.Pp
After following a fellow honker, they may be added to one or more
.Ic combos .
These are accessed via the
.Pa combos
tab and allow easy access to particular groupings.
The special combo name of one hyphen
.Sq -
will remove a honker's posts from the primary feed.
.Ss Viewing
The primary feed is accessed via the home tab, labelled
.Pa honk .
It will contain posts from all followed honkers.
Posts mentioning the user, both followed and not, are collected under the
.Pa @me
tab.
.Pp
.Lk honk-screenshot.png screen of one honk
.Ss Honking
On the home page and most other pages, there will be a button marked
.Dq it's honking time
which activates the honk form.
.Pp
The in reply to field is an advanced feature.
.Pp
One may attach a file to a post.
Images are automatically rescaled and reduced in size for federation.
.Pp
A limited subset of markdown is supported.
Bold, italics, and code blocks.
Mentioning a specfic user
.Pq @user@example.social
will send a copy of the message to them.
When replying, the author of the parent post is automatically mentioned.
.Ss zonkzone
Sometimes other users of the federation can get unruly.
The zonkzone can be of great use to restore order to one's timeline.
.Sh SEE ALSO
.Xr honk 8
.Sh STANDARDS
.Pp
.Lk https://www.w3.org/TR/activitypub/ "ActivityPub"
.Pp
.Lk https://www.w3.org/TR/activitystreams-vocabulary/ "Activity Vocabulary"
.Sh HISTORY
Started March 2019.
.Sh AUTHORS
Ted Unangst.
.Sh CAVEATS
Not all ActivityPub implementations work the same way.
.Sh BUGS
Only features.
